apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-reminder-deployment
  labels:
    app: birthday-reminder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birthday-reminder
  template:
    metadata:
      labels:
        app: birthday-reminder
    spec:
      containers:
        - name: birthday-reminder-container
          image: registry.digitalocean.com/ttadeo/birthday-reminder-app:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 30001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 30001
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: do-registry-secret
